name: Java CI with Maven

# События, которые будут запускать этот workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Определяем шаги для выполнения на CI
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Установка Java (выбираем версию JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Сборка проекта с Maven
      - name: Build with Maven
        run: mvn clean install

      # Запуск тестов
      - name: Run tests
        run: mvn test
